### ISSUE TITLE
bucket sort: worst case space is wrong? 

### ISSUE THREAD

**Issue by murraycu** [josem/bigoref#4]
bigoref.com has the worst case space for bucket sort as O(n + k). Wikipedia lists it as O(nk), which makes more sense to me:
https://en.wikipedia.org/wiki/Bucket_sort

**Comment by murraycu** [comment]
By the way, bigocheatsheet.com lists it as O(n), which I guess is not quite wrong, being a simplification of O(nk).

**Comment by josem** [comment]
Yeah, that's totally right, sorry! It should be fixed now :)
